[package]
name = "classical_and_advanced_algorithms"
version = "0.1.0"
authors = ["leviathan88 <elvisdedic@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["sorting"]
